version: "3.9"
services:
  pg:
    image: postgres:13
    restart: "always"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: prisma
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
