name: Cypress Tests

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
env:
  NEXT_PUBLIC_STRAPI_API_URL: http://188.166.82.23:1337
  NEXT_PUBLIC_STRAPI_API_GRAPHQL: http://188.166.82.23:1337/graphql

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Log env
        run: echo "${NEXT_PUBLIC_STRAPI_API_URL}&${NEXT_PUBLIC_STRAPI_API_GRAPHQL}"
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
